# Generated by Django 5.0.4 on 2024-05-03 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('baby_id', models.AutoField(primary_key=True, serialize=False)),
                ('baby_name', models.CharField(max_length=20)),
                ('baby_gender', models.CharField(max_length=20)),
                ('baby_age', models.IntegerField(default=0)),
                ('baby_location', models.CharField(max_length=20)),
                ('parents_name', models.CharField(max_length=20)),
                ('period_of_stay', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_type', models.CharField(blank=True, max_length=20, null=True)),
                ('doll_name', models.CharField(blank=True, max_length=20, null=True)),
                ('doll_price', models.IntegerField(blank=True, default=0, null=True)),
                ('doll_description', models.TextField(blank=True, max_length=30, null=True)),
                ('doll_image', models.ImageField(blank=True, null=True, upload_to='doll_images')),
            ],
        ),
        migrations.CreateModel(
            name='Forgot_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password', models.CharField(blank=True, max_length=20, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reset_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('repeat_password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_number', models.IntegerField(default=0)),
                ('date_of_arrival', models.DateField(default=django.utils.timezone.now)),
                ('timein', models.TimeField()),
                ('Attendancestatus', models.CharField(choices=[('onduty', 'onduty')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sitterform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('location', models.CharField(choices=[('kabalagala', 'kabalagala')], max_length=100)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('next_of_kin', models.CharField(max_length=200)),
                ('national_identification_number', models.CharField(max_length=200)),
                ('recommenders_name', models.CharField(max_length=200)),
                ('religon', models.CharField(blank=True, max_length=200, null=True)),
                ('level_of_education', models.CharField(choices=[('degree', 'Degree'), ('diploma', 'Diploma'), ('highschool certificate', 'Highschool certificate'), ('others', 'Others')], max_length=200)),
                ('sitter_number', models.IntegerField(default=0)),
                ('contacts', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('baby_id', models.AutoField(primary_key=True, serialize=False)),
                ('baby_picker', models.CharField(max_length=20)),
                ('date_of_departure', models.DateField(default=django.utils.timezone.now)),
                ('time_out', models.TimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('name_of_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
            ],
        ),
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('dolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('dolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('dolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.babypayment')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('baby_id', models.AutoField(primary_key=True, serialize=False)),
                ('baby_bringer', models.CharField(max_length=20)),
                ('date_of_arrival', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField()),
                ('babys_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('Assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.sitter_arrival')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_number', models.IntegerField(default=0)),
                ('date_of_departure', models.DateField(default=django.utils.timezone.now)),
                ('timeout', models.TimeField()),
                ('Attendancestatus', models.CharField(choices=[('offduty', 'offduty')], max_length=100)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.sitter_arrival')),
            ],
        ),
        migrations.AddField(
            model_name='sitter_arrival',
            name='sitter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.sitterform'),
        ),
    ]
