# Generated by Django 5.0.4 on 2024-05-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='period_of_stay',
            field=models.CharField(choices=[('half-day', 'Half-day'), ('full-day', 'Full-day'), ('monthly-halfday', 'Monthly-halfday'), ('monthly-fullday', 'Monthly-fullday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sitter_arrival',
            name='Attendancestatus',
            field=models.CharField(choices=[('On duty', 'On duty')], max_length=100),
        ),
        migrations.CreateModel(
            name='Doll_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('doll_price', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
    ]
