# Generated by Django 5.0.4 on 2024-05-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrival',
            new_name='BabyArrival',
        ),
        migrations.RenameModel(
            old_name='Departure',
            new_name='BabyDeparture',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='baby_age',
            new_name='date_of_birth',
        ),
    ]
