# Generated by Django 5.0.4 on 2024-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterform',
            name='religon',
            field=models.CharField(default='born-again', max_length=200),
            preserve_default=False,
        ),
    ]
