# Generated by Django 5.0.4 on 2024-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doll',
            name='doll_image',
        ),
        migrations.AddField(
            model_name='doll_payment',
            name='doll_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
