# Generated by Django 5.0.4 on 2024-05-12 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0002_remove_doll_doll_image_doll_payment_doll_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_type', models.CharField(choices=[('milk', 'Milk'), ('diapers', 'Diapers'), ('fruits', 'Fruits'), ('wipes', 'Wipes'), ('other', 'Other')], max_length=200)),
                ('stock_name', models.CharField(max_length=200)),
                ('stock_price', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('stock_description', models.TextField(blank=True, max_length=30, null=True)),
                ('date_stocked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='doll',
            name='doll_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doll',
            name='doll_type',
            field=models.CharField(choices=[('birds', 'Birds'), ('animals', 'Animals'), ('vehicles', 'Vehicles'), ('human', 'Human'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Stock_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('milk', 'Milk'), ('diapers', 'Diapers'), ('fruits', 'Fruits'), ('wipes', 'Wipes')], max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Doll_receipt',
        ),
    ]
