# Generated by Django 5.0.4 on 2024-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0002_rename_user_usern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='u_name',
        ),
        migrations.RenameField(
            model_name='new_pass',
            old_name='c_password',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='new_pass',
            old_name='n_password',
            new_name='new_password',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_password',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_rpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='u_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='sign_up',
            name='repeat_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reset_pass',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Usern',
        ),
    ]
