# Generated by Django 5.0.4 on 2024-05-05 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0002_rename_arrival_babyarrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
