# Generated by Django 5.0.4 on 2024-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0002_alter_babypayment_period_of_stay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_arrival',
            name='Attendancestatus',
            field=models.CharField(choices=[('On-duty', 'On-duty')], max_length=100),
        ),
    ]
