# Generated by Django 5.0.4 on 2024-05-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0002_alter_sitterform_religon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitterform',
            old_name='religon',
            new_name='religion',
        ),
    ]
