# Generated by Django 5.0.4 on 2024-05-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0003_stock_alter_doll_doll_name_alter_doll_doll_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_issue',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
