# Generated by Django 5.0.4 on 2024-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0003_remove_sign_up_u_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgot_pass',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
