# Generated by Django 5.0.4 on 2024-05-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0003_rename_religon_sitterform_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_arrival',
            name='sitter_number',
        ),
        migrations.RemoveField(
            model_name='sitter_departure',
            name='sitter_number',
        ),
        migrations.RemoveField(
            model_name='sitterform',
            name='sitter_number',
        ),
    ]
