# Generated by Django 5.0.4 on 2024-04-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0004_alter_forgot_pass_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgot_pass',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarApp.sign_in'),
        ),
    ]
