# Generated by Django 5.0.4 on 2024-05-12 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0004_rename_quantity_stock_issue_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='doll_payment',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doll_payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doll_payment',
            name='parents_name',
            field=models.CharField(default='sara', max_length=20),
            preserve_default=False,
        ),
    ]
