# Generated by Django 5.0.4 on 2024-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0005_doll_payment_amount_due_doll_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll_payment',
            name='doll_type',
            field=models.CharField(choices=[('birds', 'Birds'), ('animals', 'Animals'), ('vehicles', 'Vehicles'), ('human', 'Human'), ('other', 'Other')], default='sara', max_length=20),
            preserve_default=False,
        ),
    ]
