# Generated by Django 5.0.4 on 2024-05-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0006_alter_doll_payment_doll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypayment',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='babypayment',
            name='parent_name',
            field=models.CharField(default='sara', max_length=20),
            preserve_default=False,
        ),
    ]
