# Generated by Django 5.0.4 on 2024-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0006_rename_email_forgot_pass_email2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgot_pass',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='email1',
        ),
        migrations.AddField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
