# Generated by Django 5.0.4 on 2024-05-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0008_alter_sign_in_email_alter_sign_in_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forgot_pass',
        ),
        migrations.DeleteModel(
            name='New_pass',
        ),
        migrations.DeleteModel(
            name='Reset_pass',
        ),
        migrations.DeleteModel(
            name='Sign_up',
        ),
    ]
