# Generated by Django 5.0.4 on 2024-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0008_forgot_pass_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgot_pass',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sign_in',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
