# Generated by Django 5.0.4 on 2024-04-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0010_baby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='baby_locattion',
            new_name='baby_location',
        ),
    ]
