# Generated by Django 5.0.4 on 2024-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0011_rename_baby_locattion_baby_baby_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='repeat_password',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
