# Generated by Django 5.0.4 on 2024-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0012_alter_sign_up_repeat_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='repeat_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
