# Generated by Django 5.0.4 on 2024-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0013_alter_sign_up_repeat_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='period_of_stay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
