# Generated by Django 5.0.4 on 2024-04-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0014_alter_baby_period_of_stay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_type', models.CharField(blank=True, max_length=20, null=True)),
                ('doll_name', models.CharField(blank=True, max_length=20, null=True)),
                ('doll_price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('dolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('dolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.babypayment')),
            ],
        ),
    ]
