# Generated by Django 5.0.4 on 2024-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0015_doll_babypayment_procurement_registered_baby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='baby_fee',
        ),
        migrations.AddField(
            model_name='babypayment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
