# Generated by Django 5.0.4 on 2024-04-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0016_remove_baby_baby_fee_babypayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='doll',
            name='doll_description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doll',
            name='doll_image',
            field=models.ImageField(blank=True, null=True, upload_to='doll_images'),
        ),
        migrations.CreateModel(
            name='DollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.baby')),
                ('dolls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarApp.doll')),
            ],
        ),
    ]
